### ISSUE TITLE
Need better error handling in IngestReader

### ISSUE THREAD

**Issue by RKrahl** [icatproject/python-icat#146]
The method `icat.ingest.IngestReader.ingest()` is documented to [raise InvalidIngestFileError if any unallowed object is read from the input](https://python-icat.readthedocs.io/en/1.2.0/ingest.html#icat.ingest.IngestReader.ingest). Yet there are more possible error conditions in the ingest file that are not properly handled:

- If an invalid internal reference is used in the file, like:
  ```xml
      <datasetParameter>
        <numericValue>5.3</numericValue>
        <dataset ref="Dataset_invalid"/>
        <type name="Magnetic field" units="T"/>
      </datasetParameter>
  ```
  assuming that no Dataset is defined in the file having the id `Dataset_invalid`, a `ValueError` with an incomprehensible error message is raised:
  ```
  Traceback (most recent call last):
    ...  
    File "/home/abuild/test/python-icat-1.2.0/build/lib/icat/helper.py", line 162, in parse_attr_val
      hyphen = avs.index('-')
               ^^^^^^^^^^^^^^
  ValueError: substring not found
  ```
- If a duplicate object violating a uniqueness constraint is included in the file, like:
  ```xml
     <datasetParameter>
       <numericValue>10.0</numericValue>
       <dataset ref="Dataset_001"/>
       <type name="Reactor power" units="MW"/>
     </datasetParameter>
     <datasetParameter>
       <numericValue>17.0</numericValue>
       <dataset ref="Dataset_001"/>
       <type name="Reactor power" units="MW"/>
     </datasetParameter>
  ```
  an `ICATObjectExistsError` is raised:
  ```
  Traceback (most recent call last):
    File "/home/abuild/test/python-icat-1.2.0/doc/examples/ingest.py", line 150, in <module>
      reader.ingest(datasets)
    File "/home/abuild/test/python-icat-1.2.0/build/lib/icat/ingest.py", line 184, in ingest
      obj.create()
    File "/home/abuild/test/python-icat-1.2.0/build/lib/icat/entity.py", line 438, in create
      self.id = self.client.create(self)
                ^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/abuild/test/python-icat-1.2.0/build/lib/icat/client.py", line 356, in create
      raise translateError(e)
  icat.exception.ICATObjectExistsError: DatasetParameter exists with dataset = 'Dataset:153', type = 'ParameterType:113'
  ```

While the error message in the second example is less incomprehensible, it is particular unfortunate that the error is not raised when called with `dry_run=True`.

Both cases are unfortunate because the caller might not expect these errors, so they will not be properly handled, see for instance the [provided ingest example script](https://github.com/icatproject/python-icat/blob/54ac77c90ec35519d8a9d2df478a8e61efe1a3ce/doc/examples/ingest.py#L136).

**Comment by RKrahl** [comment]
There is yet another case that is maybe even worse: the case of a duplicate object id, like:
```xml
  <data>
    <dataset id="Dataset_1">
      <name>Dataset-A</name>
    </dataset>
    <dataset id="Dataset_1">
      <name>Dataset-B</name>
    </dataset>
    <datasetParameter>
      <numericValue>10.0</numericValue>
      <dataset ref="Dataset_1"/>
      <type name="Reactor power" units="MW"/>
    </datasetParameter>
  </data>
```
in this case, no error is raised at all.
