### ISSUE TITLE
Missing __init__.py in icat directory

### ISSUE THREAD

**Issue by dfq16044** [icatproject/python-icat#27]
When trying to build/install python-icat I got a message mentioning that __init__.py was missing and I could not have access to the python-icat module.
By adding this empty file in icat directory solve the problem.

**Comment by RKrahl** [comment]
I assume you cloned the git source repository and did something like:
```
$ python setup.py build
running build
running build_py
package init file 'icat/__init__.py' not found (or not a regular file)
creating build
creating build/lib
creating build/lib/icat
copying icat/cgi.py -> build/lib/icat
copying icat/chunkedhttp.py -> build/lib/icat
copying icat/client.py -> build/lib/icat
copying icat/config.py -> build/lib/icat
copying icat/entities.py -> build/lib/icat
copying icat/dumpfile_xml.py -> build/lib/icat
copying icat/dumpfile_yaml.py -> build/lib/icat
copying icat/entity.py -> build/lib/icat
copying icat/exception.py -> build/lib/icat
copying icat/helper.py -> build/lib/icat
copying icat/icatcheck.py -> build/lib/icat
copying icat/ids.py -> build/lib/icat
copying icat/listproxy.py -> build/lib/icat
copying icat/dumpfile.py -> build/lib/icat
copying icat/eval.py -> build/lib/icat
copying icat/query.py -> build/lib/icat
copying icat/sslcontext.py -> build/lib/icat
package init file 'icat/__init__.py' not found (or not a regular file)
running build_scripts
creating build/scripts-2.7
copying and adjusting icatdump.py -> build/scripts-2.7
copying and adjusting icatingest.py -> build/scripts-2.7
changing mode of build/scripts-2.7/icatdump.py from 644 to 755
changing mode of build/scripts-2.7/icatingest.py from 644 to 755
```
and maybe
```
$ python setup.py test
running test
running build
running build_py
package init file 'icat/__init__.py' not found (or not a regular file)
package init file 'icat/__init__.py' not found (or not a regular file)
running build_scripts
running build_test
creating tests/scripts
copying doc/examples/add-investigation-data.py -> tests/scripts
copying doc/examples/add-job.py -> tests/scripts
copying doc/examples/addfile.py -> tests/scripts
copying doc/examples/check.py -> tests/scripts
copying doc/examples/create-investigation.py -> tests/scripts
copying doc/examples/create-parametertypes.py -> tests/scripts
copying doc/examples/create-sampletype.py -> tests/scripts
copying doc/examples/downloaddata.py -> tests/scripts
copying doc/examples/dumpinvestigation.py -> tests/scripts
copying doc/examples/getversion.py -> tests/scripts
copying doc/examples/icatexport.py -> tests/scripts
copying doc/examples/icatimport.py -> tests/scripts
copying doc/examples/icatsummary.py -> tests/scripts
copying doc/examples/init-icat.py -> tests/scripts
copying doc/examples/ldapsync.py -> tests/scripts
copying doc/examples/login.py -> tests/scripts
copying doc/examples/querytest.py -> tests/scripts
copying doc/examples/wipeicat.py -> tests/scripts
copying icatdump.py -> tests/scripts
copying icatingest.py -> tests/scripts
copying doc/examples/example_data.yaml -> tests/data
copying doc/examples/icatdump.xml -> tests/data
copying doc/examples/icatdump.yaml -> tests/data
copying doc/examples/ingest-datafiles.xml -> tests/data
copying doc/examples/ingest-ds-params.xml -> tests/data
/opt/python/bin/python2.7 -m pytest
Traceback (most recent call last):
  File "/opt/python/lib/python2.7/site-packages/_pytest/config.py", line 319, in _importconftest
    mod = conftestpath.pyimport()
  File "/opt/python/lib/python2.7/site-packages/py/_path/local.py", line 650, in pyimport
    __import__(modname)
  File "/net/home/jsi/ICAT/python-icat/tests/conftest.py", line 16, in <module>
    import icat
ImportError: No module named icat
ERROR: could not load /net/home/jsi/ICAT/python-icat/tests/conftest.py

error: command '/opt/python/bin/python2.7' failed with exit status 4
```
Note the `package init file 'icat/__init__.py' not found (or not a regular file)` messages from the output.  Right?

**Comment by dfq16044** [comment]
Yes

**Comment by RKrahl** [comment]
This is not the way it is supposed to work.  `__init__.py` is created automatically during release, as it contains dynamic version information. You may use a release version from the [package home page](http://icatproject.org/user-documentation/python-icat/). If you want to use a development version, you may use the Makefile from the source directory:
```
$ make build
(cat icatinfo.py; \
echo "__revision__  = \"`git describe --always --dirty`\""; \
cat icatinit.py) > icat/__init__.py
python setup.py build
running build
running build_py
creating build
creating build/lib
creating build/lib/icat
copying icat/cgi.py -> build/lib/icat
copying icat/chunkedhttp.py -> build/lib/icat
copying icat/client.py -> build/lib/icat
copying icat/config.py -> build/lib/icat
copying icat/entities.py -> build/lib/icat
copying icat/dumpfile_xml.py -> build/lib/icat
copying icat/dumpfile_yaml.py -> build/lib/icat
copying icat/entity.py -> build/lib/icat
copying icat/exception.py -> build/lib/icat
copying icat/helper.py -> build/lib/icat
copying icat/icatcheck.py -> build/lib/icat
copying icat/ids.py -> build/lib/icat
copying icat/listproxy.py -> build/lib/icat
copying icat/dumpfile.py -> build/lib/icat
copying icat/eval.py -> build/lib/icat
copying icat/query.py -> build/lib/icat
copying icat/sslcontext.py -> build/lib/icat
copying icat/__init__.py -> build/lib/icat
running build_scripts
creating build/scripts-2.7
copying and adjusting icatdump.py -> build/scripts-2.7
copying and adjusting icatingest.py -> build/scripts-2.7
changing mode of build/scripts-2.7/icatdump.py from 644 to 755
changing mode of build/scripts-2.7/icatingest.py from 644 to 755
```

Note the first three lines from the make output, that you could also type manually at the shell as an alternative to using make:
```
(cat icatinfo.py; \
echo "__revision__  = \"`git describe --always --dirty`\""; \
cat icatinit.py) > icat/__init__.py
```

**Comment by dfq16044** [comment]
I just download the current release and checked the icat directory and it contains the __init__.py file ...
Maybe, you can put a note as few people had already this issue ...

Thanks for your help
